### ISSUE TITLE
FFmpeg.AutoGen.Redist.windows.x64 not uploaded to Nuget

### ISSUE THREAD

**Issue by erri120** [Ruslan-B/FFmpeg.AutoGen#162]
The `FFmpeg.AutoGen.Redist.windows.x64` is only in the CI artifact but on on nuget. Do you plan on pushing this to nuget or should we just use the CI artifact?

**Comment by Ruslan-B** [comment]
Short answer you shouldn't expect nuget or use CI version of ```FFmpeg.AutoGen.Redist.windows.x64```.
The long answer is:
- it is GPL(!) binaries  from [CODEX FFMPEG](https://www.gyan.dev/ffmpeg/builds/) and there are reasons why you should use GPL binaries for generation, but in production it might me unacceptable due source code licensing contamination   - I would lice to avoid delusion and confusion - this is out of scope of binding project..
- there are many way how you can build FFmpeg  binaries- i.e. multiple components like none free stuff (might need to license apart) - this is out of scope of binding project.
- this binaries x64 windows only, if we follow this rout definitely other requests are going to popup to support linux, mac os, osx, etc - this is out of scope of binding project.  

This package is meant  for CI  unit testing only - I know it is rudimentary now but going to be better over time.
@hanabi1224 correct me If I misunderstand your intension.

if you find this answer convincing enough please close the issue, otherwise, please elaborate.

**Comment by hanabi1224** [comment]
Agree that binary redistribution is out of the scope of this binding project, in the meanwhile, it will be awesome to make it a separate repo if possible.  Since shared build can be easily installed on linux/osx with their package managers, it seems more useful to have windows redistribution of the shared build. (Package managers mostly provides static build of ffmpeg only).  Correct me if I'm wrong but I believe a nuget redistribution of a shared build under lgpc license should be OK, [here](https://github.com/BtbN/FFmpeg-Builds/releases) are all kinds of windows static/shared builds under different licenses.

> [ffmpeg License Compliance Checklist](http://ffmpeg.org/legal.html)
1. Compile FFmpeg without "--enable-gpl" and without "--enable-nonfree".
1. Use dynamic linking (on windows, this means linking to dlls) for linking with FFmpeg libraries.
1. Distribute the source code of FFmpeg, no matter if you modified it or not.
1. Make sure the source code corresponds exactly to the library binaries you are distributing.
1. Run the command "git diff > changes.diff" in the root directory of the FFmpeg source code to create a file with only the changes.
1. Explain how you compiled FFmpeg, for example the configure line, in a text file added to the root directory of the source code.
1. Use tarball or a zip file for distributing the source code.
1. Host the FFmpeg source code on the same webserver as the binary you are distributing.
1. Add "This software uses code of <a href=http://ffmpeg.org>FFmpeg</a> licensed under the <a href=http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html>LGPLv2.1</a> and its source can be downloaded <a href=link_to_your_sources>here</a>" to every page in your website where there is a download link to your application.
1. Mention "This software uses libraries from the FFmpeg project under the LGPLv2.1" in your program "about box".
1. Mention in your EULA that your program uses FFmpeg under the LGPLv2.1.
1. If your EULA claims ownership over the code, you have to explicitly mention that you do not own FFmpeg, and where the relevant owners can be found.
1. Remove any prohibition of reverse engineering from your EULA.
1. Apply the same changes to all translations of your EULA.
1. Do not misspell FFmpeg (two capitals F and lowercase "mpeg").
1. Do not rename FFmpeg dlls to some obfuscated name, but adding a suffix or prefix is fine (renaming "avcodec.dll" to "MyProgDec.dll" is not fine, but to "avcodec-MyProg.dll" is).
1. Go through all the items again for any LGPL external library you compiled into FFmpeg (for example LAME).
1. Make sure your program is not using any GPL libraries (notably libx264).

**Comment by Ruslan-B** [comment]
Remove but why? 
I do not distribute binaries FFmpeg and generator doesn't execute any code from FFmpeg as well so no problem with licensing. 
This binaries are precondition for cover API completely - what kind of binaries will use end user or service provider is up to them.

**Comment by hanabi1224** [comment]
Hmm, as I understand, FFI is also a kind of 'linking' to the native library, when the linkee code (libpostproc) is under GPL, the linking code needs to be GPL as well. (This is my understanding but might be wrong tho)

**Comment by Ruslan-B** [comment]
Thing matter - back then used to be Oracle vs Google - I think would be nice to get a permission from FFmpeg consortium.

**Comment by Ruslan-B** [comment]
Reflected a bit over time - I think is better to remove binaries from the repo and put some download code into generator and example project - it will work for windows only, but linux and os x have a package manager  if not by default but by definition on dev machine.  It should close any questions with respect to licensing.  
As for dedicated project for nuget - in the past we tried to organize such one, but it used to fail for maintenance and financial reasons as if you like to create one the build of FFmpeg runs for hours. 
I know nowadays it became easy to establish one, but again I alone have limited amount of time.
