### ISSUE TITLE
Update for the new version of FFMPEG

### ISSUE THREAD

**Issue by dajuric** [Ruslan-B/FFmpeg.AutoGen#24]
Please  update for the new version of FFMPEG.
Also version of dlls is hardcoded - it should not be.
+ it won't generate *.g.cs files correctly for a new FFmpeg version (can not compile the project afterwards)

Thanks

**Comment by Ruslan-B** [comment]
You shall not pass. lol

>Please update..
Just for future, proper English - Could you please ...

> Also version of dlls is hardcoded - it should not be.
If you know how to do interop without attributes or pass dynamic values into attributes, it would be nice if you share this knowledge, besides saying  - it should not be .

Thus if you would like to use my bindings now with newer version of ffmpeg you free to do so, few options you can rename ddl's or you can change few constants in brings and recompile them.

Welcome

**Comment by dajuric** [comment]
HI Rusian-B,

   I did not mean to offend you in any way. Obviously sending messages at 2AM is not a very good idea :).

**Comment by fernando-takeshi** [comment]
You did sound like a dick :p

**Comment by Ruslan-B** [comment]
Ok, topic closed :). As I updated bindings to 3.0. It involves some labor for any update - mostly becouse of limitation in clang, to be precise there are no access to macros values. As a workaround this part emmits raw tokens from the original header file. Thus after generation you need manualy resolve inconsistencies and remove faulty ones. Besides you need to regenerate list of all exported functions in order to do proper mapping to libraries. And the last one and the first one you need to replace all include files before starting anything.
If someone still interested we can document this process.

**Comment by dajuric** [comment]
Thanks.

2016-03-09 18:19 GMT+01:00 Ruslan Balanukhin <notifications@github.com>:
