### ISSUE TITLE
Green color shift encoding RGBA to YUV420p

### ISSUE THREAD

**Issue by mbullock976** [Ruslan-B/FFmpeg.AutoGen#52]
Hi,

I was wondering If you could help. I'm currently taking converting RBGA bitmaps to YUV420p before encoding the frames with h264 codec and dumping the encoded packets to file successfully.

I'm also able to playback the h264 video file in VLC. However, there seems to be a color shift which is more apparent where grey is actually light tint of screen. I'm used a an animation video as my example which is supposed to show a blue sky in the background, however after converting the image, I'm getting an orange sky background. Do you have any ideas how I can fix this please? 

Thanks Michael

var ctx = ffmpeg.sws_getContext(
                c->width,
                c->height,
                AVPixelFormat.AV_PIX_FMT_RGBA,
                c->width,
                c->height,
                AVPixelFormat.AV_PIX_FMT_YUV420P,
                ffmpeg.SWS_FAST_BILINEAR,
                null,
                null,
                null);

/*inData is a pointer to rgb32data pulled from bitmap using lockbits*/
ffmpeg.sws_scale(ctx, inData, inLineSize, 0, c->height, frame->data, frame->linesize);

Do you happen to know if it's possible to convert rgba to yuv BEFORE calling sws_scale and before encoding packet?

**Comment by CraigN** [comment]
Most likely an issue with the input data not being in RGBA pixel format.

**Comment by Ruslan-B** [comment]
Indeed it looks like pixel format issue. I would recommend to check this issue: https://github.com/Ruslan-B/FFmpeg.AutoGen/issues/46 as it has working encoding example.
I used OpenCvSharp for the colour conversion. 
In your case if you don't wnat to depend on any other 3rd party you can try to add second convertion context (convert it back) in order to check whatever you are providing right input data and using correct settings.

**Comment by Ruslan-B** [comment]
Closing issue as rather stackoverflow.com question.
